

baseurl = "https://art.60woodvale.com/"
title = "Maeve's Awesome Art"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "violet"
  description = "The most incredible pictures you will ever see"
  copyright = "&copy;2022  MGBOOS"
  sidebarAbout = [
    "I want to be an artist",
    "![Lavender](/img/portfolio/lavender.jpeg)"
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [params.social]


